const fs = require('fs');
const c = fs.readFileSync('public/js/bundle.js', 'utf8');
console.log('ChatWidget in App:', c.includes('h(ChatWidget'));
console.log('FriendsPage tab:', c.includes('mainTab === "friends"'));
console.log('mainTab state:', c.includes('mainTabState'));
console.log('ChatWidget function:', c.includes('function ChatWidget'));
console.log('FriendsPage function:', c.includes('function FriendsPage'));
console.log('AppChatWidgetOld:', c.includes('h(SiteFooter, { onNavigate: navigate }),'));
console.log('MiCuentaOld:', c.includes('detailState = React.useState(null);'));
console.log('miCuentaReturnOld:', c.includes('return h("div", { className: "movies-page" }'));
console.log('AppChatWidgetNew:', c.includes('user ? h(ChatWidget'));
console.log('miCuentaReturnNew:', c.includes('const mainTabState = React.useState'));
console.log('miCuentaNew:', c.includes('const mainTabState = React.useState("movies");'));